name: Generar Animación Snake

on:
  # Se ejecuta automáticamente cada 24 horas
  schedule:
    - cron: "0 0 * * *"
  # Permite ejecutar manualmente desde la pestaña Actions
  workflow_dispatch:
  # Se ejecuta en cada push a la rama principal
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Genera las animaciones snake en SVG
      - name: Generar github-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Sube los SVGs a la rama 'output'
      - name: Subir SVGs a la rama output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
